export type TipoCliente = "Constructora" | "Gobierno" | "Particular" | "Inmobiliaria" | "Industrial";
export type EstatusCliente = "Activo" | "Inactivo" | "Prospecto" | "Bloqueado";
export type CalificacionCliente = "A" | "B" | "C";

export interface Cliente {
  id: string;
  razonSocial: string;
  nombreComercial: string;
  rfc: string;
  domicilio: string;
  colonia: string;
  municipio: string;
  estado: string;
  cp: string;
  contacto: string;
  cargo: string;
  telefono: string;
  email: string;
  tipoCliente: TipoCliente;
  vendedorAsignado: string;
  limiteCredito: number;
  saldoPendiente: number;
  diasCredito: number;
  ultimaCompra: string;
  totalComprasAnio: number;
  m3Acumulados: number;
  estatus: EstatusCliente;
  calificacion: CalificacionCliente;
  fechaAlta: string;
  notas: string;
}

export const clientes: Cliente[] = [
  {
    id: "CL-001",
    razonSocial: "Grupo Constructoras del Norte S.A. de C.V.",
    nombreComercial: "GCN Constructoras",
    rfc: "GCN890415TU6",
    domicilio: "Av. Constitución 2800 Int. 12",
    colonia: "Col. Del Valle",
    municipio: "Monterrey",
    estado: "Nuevo León",
    cp: "64000",
    contacto: "Ing. Carlos Herrera López",
    cargo: "Director de Proyectos",
    telefono: "81 8344 2200",
    email: "c.herrera@gcnconstructoras.mx",
    tipoCliente: "Constructora",
    vendedorAsignado: "Ana López",
    limiteCredito: 850000,
    saldoPendiente: 312000,
    diasCredito: 45,
    ultimaCompra: "2026-06-01",
    totalComprasAnio: 1840000,
    m3Acumulados: 9200,
    estatus: "Activo",
    calificacion: "A",
    fechaAlta: "2020-02-10",
    notas: "Cliente preferente. Descuento especial en volúmenes > 500m3.",
  },
  {
    id: "CL-002",
    razonSocial: "Inmobiliaria Cumbres Desarrollo S.A. de C.V.",
    nombreComercial: "Cumbres Desarrollo",
    rfc: "ICD950801MN3",
    domicilio: "Blvd. Acueducto 2900 Piso 3",
    colonia: "Carretera Nacional",
    municipio: "Monterrey",
    estado: "Nuevo León",
    cp: "64810",
    contacto: "Lic. Patricia Salas Vázquez",
    cargo: "Gerente de Compras",
    telefono: "81 8180 5544",
    email: "p.salas@cumbresdesa.mx",
    tipoCliente: "Inmobiliaria",
    vendedorAsignado: "Carlos Ortiz",
    limiteCredito: 1200000,
    saldoPendiente: 580000,
    diasCredito: 30,
    ultimaCompra: "2026-05-28",
    totalComprasAnio: 2650000,
    m3Acumulados: 13250,
    estatus: "Activo",
    calificacion: "A",
    fechaAlta: "2019-08-15",
    notas: "Proyecto residencial Cumbres Elite. Entregas semanales.",
  },
  {
    id: "CL-003",
    razonSocial: "Ayuntamiento de San Nicolás de los Garza",
    nombreComercial: "Municipio San Nicolás",
    rfc: "ASN780115KP8",
    domicilio: "Av. Nogalar 109",
    colonia: "Industrial",
    municipio: "San Nicolás de los Garza",
    estado: "Nuevo León",
    cp: "66480",
    contacto: "Arq. Mario Fuentes Reyes",
    cargo: "Director de Obras Públicas",
    telefono: "81 8350 1100",
    email: "m.fuentes@sannicolas.gob.mx",
    tipoCliente: "Gobierno",
    vendedorAsignado: "Ventas MTY",
    limiteCredito: 2000000,
    saldoPendiente: 124000,
    diasCredito: 60,
    ultimaCompra: "2026-05-15",
    totalComprasAnio: 980000,
    m3Acumulados: 4900,
    estatus: "Activo",
    calificacion: "B",
    fechaAlta: "2021-01-20",
    notas: "Licitaciones anuales. Requiere factura SAT y fianza.",
  },
  {
    id: "CL-004",
    razonSocial: "Edificaciones Monterrey S.A. de C.V.",
    nombreComercial: "EM Edificaciones",
    rfc: "EMO010612GH5",
    domicilio: "Río Amazonas 430",
    colonia: "Del Valle",
    municipio: "San Pedro Garza García",
    estado: "Nuevo León",
    cp: "66220",
    contacto: "Ing. Roberto Castro Saldívar",
    cargo: "Gerente General",
    telefono: "81 8378 9900",
    email: "r.castro@edificacionesmty.mx",
    tipoCliente: "Constructora",
    vendedorAsignado: "Ana López",
    limiteCredito: 600000,
    saldoPendiente: 0,
    diasCredito: 30,
    ultimaCompra: "2026-04-12",
    totalComprasAnio: 720000,
    m3Acumulados: 3600,
    estatus: "Activo",
    calificacion: "A",
    fechaAlta: "2022-05-03",
    notas: "Pagos siempre a tiempo. Cliente leal.",
  },
  {
    id: "CL-005",
    razonSocial: "Parques Industriales Apodaca S.A. de C.V.",
    nombreComercial: "PI Apodaca",
    rfc: "PIA980320JR2",
    domicilio: "Carretera Apodaca-Zuazua Km. 4",
    colonia: "Parque Industrial",
    municipio: "Apodaca",
    estado: "Nuevo León",
    cp: "66600",
    contacto: "Ing. Jorge Moreno Sandoval",
    cargo: "Supervisor de Planta",
    telefono: "81 8386 4422",
    email: "j.moreno@piapodaca.mx",
    tipoCliente: "Industrial",
    vendedorAsignado: "Carlos Ortiz",
    limiteCredito: 1500000,
    saldoPendiente: 845000,
    diasCredito: 45,
    ultimaCompra: "2026-06-03",
    totalComprasAnio: 3120000,
    m3Acumulados: 15600,
    estatus: "Activo",
    calificacion: "A",
    fechaAlta: "2018-11-08",
    notas: "Mayor cliente industrial. Proyecto expansión nave 4.",
  },
  {
    id: "CL-006",
    razonSocial: "Desarrolladora Cielo Nuevo S.A. de C.V.",
    nombreComercial: "Cielo Nuevo",
    rfc: "DCN110905LV9",
    domicilio: "Lincoln 330 Desp. 10",
    colonia: "Chepevera",
    municipio: "Monterrey",
    estado: "Nuevo León",
    cp: "64030",
    contacto: "Lic. Fernanda Garza Montoya",
    cargo: "Directora Comercial",
    telefono: "81 8342 7711",
    email: "f.garza@cielonuevo.mx",
    tipoCliente: "Inmobiliaria",
    vendedorAsignado: "Ana López",
    limiteCredito: 400000,
    saldoPendiente: 380000,
    diasCredito: 30,
    ultimaCompra: "2026-05-20",
    totalComprasAnio: 560000,
    m3Acumulados: 2800,
    estatus: "Activo",
    calificacion: "B",
    fechaAlta: "2023-03-14",
    notas: "Saldo cercano a límite. Solicitar pago antes de nueva entrega.",
  },
  {
    id: "CL-007",
    razonSocial: "Ricardo Alfredo Salas Hinojosa",
    nombreComercial: "Construcción Salas",
    rfc: "SAHR790604NE1",
    domicilio: "Juárez 122 Sur",
    colonia: "Centro",
    municipio: "Escobedo",
    estado: "Nuevo León",
    cp: "66050",
    contacto: "Ricardo Salas",
    cargo: "Propietario",
    telefono: "81 1123 4499",
    email: "rsalas@gmail.com",
    tipoCliente: "Particular",
    vendedorAsignado: "Ventas MTY",
    limiteCredito: 80000,
    saldoPendiente: 22000,
    diasCredito: 15,
    ultimaCompra: "2026-04-28",
    totalComprasAnio: 145000,
    m3Acumulados: 725,
    estatus: "Activo",
    calificacion: "B",
    fechaAlta: "2024-01-09",
    notas: "",
  },
  {
    id: "CL-008",
    razonSocial: "Concretos y Acabados del Noreste S.A. de C.V.",
    nombreComercial: "CAN Noreste",
    rfc: "CAN001205TZ4",
    domicilio: "Av. Pablo Livas 3300",
    colonia: "Mitras Norte",
    municipio: "Guadalupe",
    estado: "Nuevo León",
    cp: "67130",
    contacto: "Ing. Alejandro Vega Torres",
    cargo: "Compras",
    telefono: "81 8371 5500",
    email: "a.vega@cannoreste.mx",
    tipoCliente: "Constructora",
    vendedorAsignado: "Carlos Ortiz",
    limiteCredito: 500000,
    saldoPendiente: 0,
    diasCredito: 30,
    ultimaCompra: "2026-02-14",
    totalComprasAnio: 110000,
    m3Acumulados: 550,
    estatus: "Inactivo",
    calificacion: "B",
    fechaAlta: "2021-06-22",
    notas: "Sin actividad reciente. Retomar contacto.",
  },
  {
    id: "CL-009",
    razonSocial: "Infraestructura Urbana NL S.A. de C.V.",
    nombreComercial: "Infraurbana NL",
    rfc: "IUN150830WX3",
    domicilio: "Av. Morones Prieto 1620 Piso 2",
    colonia: "Lomas de San Francisco",
    municipio: "Monterrey",
    estado: "Nuevo León",
    cp: "64710",
    contacto: "Dr. Marco Elizondo Cantú",
    cargo: "VP de Operaciones",
    telefono: "81 8388 8800",
    email: "m.elizondo@infraurbanaNL.mx",
    tipoCliente: "Constructora",
    vendedorAsignado: "Ventas MTY",
    limiteCredito: 3000000,
    saldoPendiente: 1250000,
    diasCredito: 60,
    ultimaCompra: "2026-06-05",
    totalComprasAnio: 4800000,
    m3Acumulados: 24000,
    estatus: "Activo",
    calificacion: "A",
    fechaAlta: "2017-09-01",
    notas: "Contrato marco 2026. Tarifa preferencial acordada.",
  },
  {
    id: "CL-010",
    razonSocial: "Logística y Transportes Regio S.A. de C.V.",
    nombreComercial: "LT Regio",
    rfc: "LTR121010SQ7",
    domicilio: "Periferico Sur 4900 Bodega 8",
    colonia: "Parque Industrial Las Américas",
    municipio: "Monterrey",
    estado: "Nuevo León",
    cp: "64988",
    contacto: "C.P. Susana Niño Valdés",
    cargo: "Administración",
    telefono: "81 8290 7700",
    email: "s.nino@ltregio.mx",
    tipoCliente: "Industrial",
    vendedorAsignado: "Ana López",
    limiteCredito: 200000,
    saldoPendiente: 210000,
    diasCredito: 30,
    ultimaCompra: "2026-05-10",
    totalComprasAnio: 340000,
    m3Acumulados: 1700,
    estatus: "Bloqueado",
    calificacion: "C",
    fechaAlta: "2023-07-18",
    notas: "Saldo excede límite. Bloqueo preventivo hasta regularizar.",
  },
  {
    id: "CL-011",
    razonSocial: "Obra y Desarrollo Metropolitano S.A. de C.V.",
    nombreComercial: "ODM Construcción",
    rfc: "ODM200114HB0",
    domicilio: "Espinoza 880 Pte.",
    colonia: "Centro",
    municipio: "Monterrey",
    estado: "Nuevo León",
    cp: "64000",
    contacto: "Arq. Daniela Ríos Almaguer",
    cargo: "Coordinadora de Proyectos",
    telefono: "81 2250 1188",
    email: "d.rios@odm.mx",
    tipoCliente: "Constructora",
    vendedorAsignado: "Carlos Ortiz",
    limiteCredito: 0,
    saldoPendiente: 0,
    diasCredito: 0,
    ultimaCompra: "—",
    totalComprasAnio: 0,
    m3Acumulados: 0,
    estatus: "Prospecto",
    calificacion: "B",
    fechaAlta: "2026-05-30",
    notas: "Primer contacto en expo Expoconstrucción 2026. Cotización enviada.",
  },
  {
    id: "CL-012",
    razonSocial: "Grupo de Vivienda Popular del Norte S.A. de C.V.",
    nombreComercial: "Vivienda Popular Norte",
    rfc: "GVP030828KL5",
    domicilio: "Av. Francisco I. Madero 440",
    colonia: "Col. Obrera",
    municipio: "Monterrey",
    estado: "Nuevo León",
    cp: "64010",
    contacto: "Ing. Raúl Quintero Bravo",
    cargo: "Gerente de Construcción",
    telefono: "81 8371 3300",
    email: "r.quintero@gvpnorte.mx",
    tipoCliente: "Constructora",
    vendedorAsignado: "Ventas MTY",
    limiteCredito: 700000,
    saldoPendiente: 95000,
    diasCredito: 30,
    ultimaCompra: "2026-05-31",
    totalComprasAnio: 1290000,
    m3Acumulados: 6450,
    estatus: "Activo",
    calificacion: "A",
    fechaAlta: "2020-10-07",
    notas: "Proyecto Residencial Los Encinos, Escobedo.",
  },
];

export const tiposCliente: TipoCliente[] = ["Constructora", "Gobierno", "Particular", "Inmobiliaria", "Industrial"];
export const estatusCliente: EstatusCliente[] = ["Activo", "Inactivo", "Prospecto", "Bloqueado"];
export const vendedores = ["Ana López", "Carlos Ortiz", "Ventas MTY"];
